inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*
    - node_modules/**/*
    - config/puma.rb


Layout/LineLength:
  Exclude:
    - 'config/initializers/devise'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/StringLiterals:
  Exclude:
    - 'config/environments/production.rb'
    - 'config/spring.rb'
    
